#!/bin/bash
set -eux -o pipefail
export PATH="${PATH}:/opt/bin"

# Get kubeadm to write out keys, certificates, manifests, and the kubelet config.
# timeout 10 because kubeadm will wait for kubelet to start which will never succeed since
# we need to set the api settings down below
# TODO: instead of a dumb timeout, we migth be able to be a bit smarter and make sure
# /var/lib/kubelet/config.yaml + certs are all written out
timeout 10 kubeadm -v9 --config /tmp/kubeadm-join-config.yaml join phase kubelet-start ||:

# Compute and apply all required settings.
API="$(awk '/apiServerEndpoint:/{ print "https://"$2 }' /tmp/kubeadm-join-config.yaml)"
CA="$(base64 -w 0 /etc/kubernetes/pki/ca.crt)"
TOKEN="$(awk '/token:/{ print $2 }' /tmp/kubeadm-join-config.yaml)"
DNS="$(awk '/clusterDNS:/ { getline; print $2 }' /var/lib/kubelet/config.yaml)"

apiclient set \
  kubernetes.api-server="${API}" \
  kubernetes.cluster-certificate="${CA}" \
  kubernetes.cluster-dns-ip="${DNS}" \
  kubernetes.bootstrap-token="${TOKEN}" \
  kubernetes.authentication-mode="tls" \
  kubernetes.standalone-mode="false"
