---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-anywhere-test
  labels:
    app: eks-anywhere-test
spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
