# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

batch:
  fast-fail: true
  build-graph:
    - identifier: emissary_ingress_emissary_amd64
      buildspec: buildspec.yml
      env:
        type: LINUX_CONTAINER
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IMAGE_TAG_SUFFIX: "-amd64"
          IMAGE_PLATFORMS: linux/amd64    
          HAS_HELM_CHART: ""      
    - identifier: emissary_ingress_emissary_arm64
      buildspec: buildspec.yml
      env:
        type: ARM_CONTAINER
        compute-type: BUILD_GENERAL1_LARGE
        variables:
          IMAGE_TAG_SUFFIX: "-arm64"
          IMAGE_PLATFORMS: linux/arm64
          BINARY_PLATFORMS: linux/arm64
          HAS_S3_ARTIFACTS: ""
          HAS_HELM_CHART: ""
    - identifier: emissary_ingress_emissary
      buildspec: buildspecs/images.yml
      depend-on:
        - emissary_ingress_emissary_amd64
        - emissary_ingress_emissary_arm64
      env:
        type: ARM_CONTAINER
        compute-type: BUILD_GENERAL1_SMALL
        variables:
          RELEASE_TARGETS: "combine-images helm/push"
          BINARY_TARGETS: ""
          LICENSES_TARGETS_FOR_PREREQ: ""
          HANDLE_DEPENDENCIES_TARGET: ""
