version: 0.2

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists) && make check-for-release-branch-skip -C $PROJECT_PATH; then make release -C $PROJECT_PATH; fi
