version: 0.2

env:
  variables:
    IMAGE_NAMES: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make release -C $PROJECT_PATH; fi
