version: 0.2

env:
  variables:
    RELEASE_TARGETS: "combine-images helm/push"
    BINARY_TARGETS: ""
    LICENSES_TARGETS_FOR_PREREQ: ""
    HANDLE_DEPENDENCIES_TARGET: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make release -C $PROJECT_PATH; fi
