version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "github-eks-distro-pr-bot:github-token"

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - make upgrade -C tools/version-tracker PROJECT=aws/eks-distro VERBOSITY=6
