version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "github-eks-distro-pr-bot:github-token"

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - echo "CHECKSUMS -text merge=union" > .gitattributes
    - PROJECT_NAME=${PROJECT_PATH#"projects/"}
    - make upgrade -C tools/version-tracker PROJECT=$PROJECT_NAME VERBOSITY=6
