version: 0.2

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - make release -C $PROJECT_PATH

artifacts:
  files:
  - $PROJECT_PATH/$CODEBUILD_BUILD_NUMBER-$CODEBUILD_RESOLVED_SOURCE_VERSION/artifacts/*.gz