apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
spec:
  nodeName: eksa-node04
  containers:
  - command:
       - sh
       - -c
       - 'while true; do echo "`date` [`hostname`] Goodbye from eksa-node04." >> /mnt/openebs-csi/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/openebs-csi
      name: demo-vol
  volumes:
  - name: demo-vol
    persistentVolumeClaim:
      claimName: small-pvc
