{{- if .Values.rufio.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Values.rufio.managerRoleName }}
rules:
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements/finalizers
  verbs:
  - update
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - baseboardmanagements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs/finalizers
  verbs:
  - update
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmcjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks/finalizers
  verbs:
  - update
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - bmctasks/status
  verbs:
  - get
  - patch
  - update
{{- end }}
