{{- if .Values.tinkController.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.tinkController.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.tinkController.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tinkController.name }}
    namespace: {{ .Values.namespace }}
{{- end }}
