{{- if .Values.tinkController.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.tinkController.roleName }}
rules:
  - apiGroups:
      - tinkerbell.org
    resources:
      - hardware
      - hardware/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - templates
      - templates/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - workflows
      - workflows/status
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
