  configurations:
  - name: sourceRegistry
  - name: externalURL
    default: "https://127.0.0.1:30003"
  - name: imagePullPolicy
    default: "IfNotPresent"
  - name: logLevel
    default: "info"
  - name: harborAdminPassword
    default: "Harbor12345"
  - name: secretKey
    required: true
  - name: expose.type
    default: "nodePort"
  - name: expose.tls.enabled
    default: "true"
  - name: expose.tls.certSource
    default: secret
  - name: expose.tls.auto.commonName
    default: ""
  - name: expose.tls.secret.secretName
    default: harbor-tls-secret
  - name: expose.nodePort.name
    default: harbor
  - name: expose.nodePort.ports.http.port
    default: "80"
  - name: expose.nodePort.ports.http.nodePort
    default: "30002"
  - name: expose.nodePort.ports.https.port
    default: "443"
  - name: expose.nodePort.ports.https.nodePort
    default: "30003"
  - name: expose.loadBalancer.name
    default: harbor
  - name: expose.loadBalancer.IP
    default: ""
  - name: expose.loadBalancer.ports.httpPort
    default: "80"
  - name: expose.loadBalancer.ports.httpsPort
    default: "30002"
  - name: internalTLS.enabled
    default: "true"
  - name: persistence.resourcePolicy
    default: keep
  - name: persistence.persistentVolumeClaim.registry.size
    default: "5Gi"
  - name: persistence.persistentVolumeClaim.registry.storageClass
    default: ""
  - name: persistence.persistentVolumeClaim.jobservice.size
    default: "1Gi"
  - name: persistence.persistentVolumeClaim.jobservice.storageClass
    default: ""
  - name: persistence.persistentVolumeClaim.database.size
    default: "1Gi"
  - name: persistence.persistentVolumeClaim.database.storageClass
    default: ""
  - name: persistence.persistentVolumeClaim.redis.size
    default: "1Gi"
  - name: persistence.persistentVolumeClaim.redis.storageClass
    default: ""
  - name: persistence.persistentVolumeClaim.trivy.size
    default: "5Gi"
  - name: persistence.persistentVolumeClaim.trivy.storageClass
    default: ""
