name: codeql-analysis
on:
  pull_request_target:
    types: [opened]
jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go, python
      - name: Build container images and binary archives
        run: |
          make build
          make release
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          output: codeql-results
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeql-results/codeql-sarif/*.sarif
