{{- if .Values.tinkController.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.tinkController.tinkLeaderElectionRoleBindingName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.tinkController.tinkLeaderElectionRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tinkController.name }}
    namespace: {{ .Values.namespace }}
{{- end }}
