version: 0.2

env:
  variables:
    HAS_S3_ARTIFACTS: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make binaries haproxy/images/push kindnetd/images/push kind-base/images/push -C $PROJECT_PATH; fi
