version: 0.2

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make validate-checksums upload-artifacts -C $PROJECT_PATH; fi
