version: 0.2

env:
  variables:
    HAS_S3_ARTIFACTS: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make binaries kind-base-versioned/images/push kind-node/images/push BINARY_TARGET_FILES=kind HAS_LICENSES=false -C $PROJECT_PATH; fi
