version: 0.2

env:
  variables:
    BINARY_TARGET_FILES: "kind"
    HAS_S3_ARTIFACTS: ""
    HAS_LICENSES: "false"
    RELEASE_TARGETS: "binaries kind-base-versioned/images/push kind-node/images/push"


phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make release -C $PROJECT_PATH; fi
