{{- if .Values.loadBalancer.enabled -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tinkerbell-pool
  namespace: {{ .Values.namespace }}
spec:
  addresses:
  - {{ .Values.loadBalancer.ip }}/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tinkerbell-l2-advertisement
  namespace: {{ .Values.namespace }}
---
{{- end -}}
