version: 0.2

env:
  variables:
    IMAGE_REPO: public.ecr.aws/l0g8r8j6
    
phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make release -C $PROJECT_PATH; fi
