apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-eks-add-ons
  labels:
    app: test-eks-add-ons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-eks-add-ons
  template:
    metadata:
      labels:
        app: test-eks-add-ons
    spec:
      containers:
        - name: hello
          image: {{ .Values.registry }}/test-eks-add-ons:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SECRET_NAME
              value: bar
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /config
              name: foo
            - mountPath: /secrets
              name: bar
      volumes:
        - name: foo
          configMap:
            name: foo
        - name: bar
          secret:
            secretName: bar
