# Default values for tinkerbell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: tink-system
createNamespace: true

boots:
  deploy: true
  name: boots
  image: quay.io/tinkerbell/boots:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: ["-dhcp-addr=0.0.0.0:67"]
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: boots-role
  roleBindingName: boots-rolebinding
  env: []

hegel:
  deploy: true
  name: hegel
  image: quay.io/tinkerbell/hegel:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  port:
    hostPortEnabled: true
    hostPort: 50061
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: hegel-role
  roleBindingName: hegel-rolebinding

tinkController:
  deploy: true
  name: tink-controller-manager
  image: quay.io/tinkerbell/tink-controller:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-controller-manager-role
  roleBindingName: tink-controller-manager-rolebinding
  tinkLeaderElectionRoleName: tink-leader-election-role
  tinkLeaderElectionRoleBindingName: tink-leader-election-rolebinding

tinkServer:
  deploy: true
  name: tink-server
  image: quay.io/tinkerbell/tink-server:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  port:
    hostPortEnabled: true
    hostPort: 42113
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-server-role
  roleBindingName: tink-server-rolebinding
