version: 0.2

env:
  variables:
    IMAGE_REPO: public.ecr.aws/f5b7k4z5

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh
    - git config --global credential.helper '!aws codecommit credential-helper $@'
    - git config --global credential.UseHttpPath true

  build:
    commands:
    - make release -C $PROJECT_PATH
