---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-anywhere-test
  labels:
    app: eks-anywhere-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-anywhere-test
  template:
    metadata:
      labels:
        app: eks-anywhere-test
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/l0g8r8j6/eks-anywhere-test:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /config
          name: foo
        - mountPath: /secrets
          name: bar
      volumes:
      - name: foo
        configMap:
          name: foo
      - name: bar
        secret:
          secretName: bar
---
apiVersion: v1
kind: Service
metadata:
  name: eks-anywhere-test
spec:
  type: NodePort
  selector:
    app: eks-anywhere-test
  ports:
    - port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: bar
data:
  bar: cXV1eA== # quux
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
  foo: baz
