version: 0.2

env:
  variables:
    RELEASE_TARGETS: "combine-artifacts upload-artifacts"
    UPLOAD_DO_NOT_DELETE: "false"
    SIMPLE_CREATE_TARBALLS: "false"
    BINARY_TARGETS: ""
    LICENSES_TARGETS_FOR_PREREQ: ""
    HANDLE_DEPENDENCIES_TARGET: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists) && make check-for-release-branch-skip -C $PROJECT_PATH; then make release -C $PROJECT_PATH; fi
