From 9bc406a67f446fdddf22d1c8b4c3237db655cfbd Mon Sep 17 00:00:00 2001
From: Prow Bot <prow@amazonaws.com>
Date: Wed, 10 Jan 2024 15:27:04 -0800
Subject: [PATCH 1/3] Update image repo

---
 charts/opentelemetry-collector/templates/_pod.tpl | 6 +++---
 charts/opentelemetry-collector/values.schema.json | 4 ++++
 charts/opentelemetry-collector/values.yaml        | 7 ++++---
 3 files changed, 11 insertions(+), 6 deletions(-)

diff --git a/charts/opentelemetry-collector/templates/_pod.tpl b/charts/opentelemetry-collector/templates/_pod.tpl
index 0a6da5c..0cbfd16 100644
--- a/charts/opentelemetry-collector/templates/_pod.tpl
+++ b/charts/opentelemetry-collector/templates/_pod.tpl
@@ -24,12 +24,12 @@ containers:
       {{- toYaml .Values.securityContext | nindent 6 }}
       {{- end }}
     {{- if .Values.image.digest }}
-    image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
+    image: "{{ .Values.sourceRegistry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}"
     {{- else }}
-    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
+    image: "{{ .Values.sourceRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
     {{- end }}
     imagePullPolicy: {{ .Values.image.pullPolicy }}
-    
+
     {{- $ports := include "opentelemetry-collector.podPortsConfig" . }}
     {{- if $ports }}
     ports:
diff --git a/charts/opentelemetry-collector/values.schema.json b/charts/opentelemetry-collector/values.schema.json
index 9819327..0a1684a 100644
--- a/charts/opentelemetry-collector/values.schema.json
+++ b/charts/opentelemetry-collector/values.schema.json
@@ -23,6 +23,10 @@
     "global": {
       "type": "object"
     },
+    "sourceRegistry": {
+      "description": "Override source registry of the helm chart.",
+      "type": "string"
+    },
     "nameOverride": {
       "description": "Override name of the chart used in Kubernetes object names.",
       "type": "string"
diff --git a/charts/opentelemetry-collector/values.yaml b/charts/opentelemetry-collector/values.yaml
index 28dd7c7..28abd61 100644
--- a/charts/opentelemetry-collector/values.yaml
+++ b/charts/opentelemetry-collector/values.yaml
@@ -2,6 +2,7 @@
 # This is a YAML-formatted file.
 # Declare variables to be passed into your templates.
 
+sourceRegistry: "783794618700.dkr.ecr.us-west-2.amazonaws.com"
 nameOverride: ""
 fullnameOverride: ""
 
@@ -163,17 +164,17 @@ config:
 
 image:
   # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
-  repository: otel/opentelemetry-collector-contrib
+  repository: adot/aws-observability/aws-otel-collector
   pullPolicy: IfNotPresent
   # Overrides the image tag whose default is the chart appVersion.
   tag: ""
   # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
-  digest: ""
+  digest: {{aws-observability/aws-otel-collector}}
 imagePullSecrets: []
 
 # OpenTelemetry Collector executable
 command:
-  name: otelcol-contrib
+  name: awscollector
   extraArgs: []
 
 serviceAccount:
-- 
2.43.0

