From 6adc11d257ca634e2c321fce7965812a0276a1ef Mon Sep 17 00:00:00 2001
From: "Ostosh, Ivy" <ivyjin@amazon.com>
Date: Thu, 29 Sep 2022 20:12:32 -0500
Subject: [PATCH] Update image repo

---
 charts/opentelemetry-collector/templates/_pod.tpl | 2 +-
 charts/opentelemetry-collector/values.schema.json | 7 +++++++
 charts/opentelemetry-collector/values.yaml        | 8 ++++----
 3 files changed, 12 insertions(+), 5 deletions(-)

diff --git a/charts/opentelemetry-collector/templates/_pod.tpl b/charts/opentelemetry-collector/templates/_pod.tpl
index 4eebc0b..9c6bed9 100644
--- a/charts/opentelemetry-collector/templates/_pod.tpl
+++ b/charts/opentelemetry-collector/templates/_pod.tpl
@@ -18,7 +18,7 @@ containers:
       {{- end }}
     securityContext:
       {{- toYaml .Values.securityContext | nindent 6 }}
-    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
+    image: "{{ .Values.sourceRegistry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}"
     imagePullPolicy: {{ .Values.image.pullPolicy }}
     ports:
       {{- range $key, $port := .Values.ports }}
diff --git a/charts/opentelemetry-collector/values.schema.json b/charts/opentelemetry-collector/values.schema.json
index 3074c52..9b5eae1 100644
--- a/charts/opentelemetry-collector/values.schema.json
+++ b/charts/opentelemetry-collector/values.schema.json
@@ -23,6 +23,10 @@
     "global": {
       "type": "object"
     },
+    "sourceRegistry": {
+      "description": "Override source registry of the helm chart.",
+      "type": "string"
+    },
     "nameOverride": {
       "description": "Override name of the chart used in Kubernetes object names.",
       "type": "string"
@@ -94,6 +98,9 @@
         "tag": {
           "type": "string"
         },
+        "digest": {
+          "type": "string"
+        },
         "pullPolicy": {
           "type": "string",
           "enum": [
diff --git a/charts/opentelemetry-collector/values.yaml b/charts/opentelemetry-collector/values.yaml
index 5970c77..c209222 100644
--- a/charts/opentelemetry-collector/values.yaml
+++ b/charts/opentelemetry-collector/values.yaml
@@ -2,6 +2,7 @@
 # This is a YAML-formatted file.
 # Declare variables to be passed into your templates.
 
+sourceRegistry: "783794618700.dkr.ecr.us-west-2.amazonaws.com"
 nameOverride: ""
 fullnameOverride: ""
 
@@ -112,15 +113,14 @@ config:
 
 image:
   # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
-  repository: otel/opentelemetry-collector-contrib
+  repository: adot/aws-observability/aws-otel-collector
   pullPolicy: IfNotPresent
-  # Overrides the image tag whose default is the chart appVersion.
-  tag: ""
+  digest: {{aws-observability/aws-otel-collector}}
 imagePullSecrets: []
 
 # OpenTelemetry Collector executable
 command:
-  name: otelcol-contrib
+  name: awscollector
   extraArgs: []
 
 serviceAccount:
-- 
2.31.0

