From b3736cd6740dc7dff15eccfa3f740d14a9e8cb4b Mon Sep 17 00:00:00 2001
From: "Ostosh, Ivy" <ivyjin@amazon.com>
Date: Fri, 27 Jan 2023 14:53:53 -0600
Subject: [PATCH 2/3] Add namespace to charts

---
 charts/opentelemetry-collector/templates/configmap-agent.yaml | 2 +-
 .../templates/configmap-statefulset.yaml                      | 2 +-
 charts/opentelemetry-collector/templates/configmap.yaml       | 2 +-
 charts/opentelemetry-collector/templates/daemonset.yaml       | 2 +-
 charts/opentelemetry-collector/templates/deployment.yaml      | 2 +-
 charts/opentelemetry-collector/templates/hpa.yaml             | 2 +-
 charts/opentelemetry-collector/templates/ingress.yaml         | 2 +-
 charts/opentelemetry-collector/templates/pdb.yaml             | 2 +-
 charts/opentelemetry-collector/templates/podmonitor.yaml      | 2 +-
 charts/opentelemetry-collector/templates/prometheusrule.yaml  | 2 +-
 charts/opentelemetry-collector/templates/service.yaml         | 2 +-
 charts/opentelemetry-collector/templates/serviceaccount.yaml  | 2 +-
 charts/opentelemetry-collector/templates/servicemonitor.yaml  | 2 +-
 charts/opentelemetry-collector/templates/statefulset.yaml     | 2 +-
 charts/opentelemetry-collector/values.schema.json             | 4 ++++
 charts/opentelemetry-collector/values.yaml                    | 1 +
 16 files changed, 19 insertions(+), 14 deletions(-)

diff --git a/charts/opentelemetry-collector/templates/configmap-agent.yaml b/charts/opentelemetry-collector/templates/configmap-agent.yaml
index dde2b52..2658f7b 100644
--- a/charts/opentelemetry-collector/templates/configmap-agent.yaml
+++ b/charts/opentelemetry-collector/templates/configmap-agent.yaml
@@ -3,7 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/configmap-statefulset.yaml b/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
index 5b6daed..70d4ffe 100644
--- a/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
+++ b/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
@@ -3,7 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-statefulset
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/configmap.yaml b/charts/opentelemetry-collector/templates/configmap.yaml
index b0c7747..610179b 100644
--- a/charts/opentelemetry-collector/templates/configmap.yaml
+++ b/charts/opentelemetry-collector/templates/configmap.yaml
@@ -3,7 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/daemonset.yaml b/charts/opentelemetry-collector/templates/daemonset.yaml
index 2fe385e..b9a51e8 100644
--- a/charts/opentelemetry-collector/templates/daemonset.yaml
+++ b/charts/opentelemetry-collector/templates/daemonset.yaml
@@ -3,7 +3,7 @@ apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- if .Values.annotations }}
diff --git a/charts/opentelemetry-collector/templates/deployment.yaml b/charts/opentelemetry-collector/templates/deployment.yaml
index 113d11c..af29c94 100644
--- a/charts/opentelemetry-collector/templates/deployment.yaml
+++ b/charts/opentelemetry-collector/templates/deployment.yaml
@@ -3,7 +3,7 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- if .Values.annotations }}
diff --git a/charts/opentelemetry-collector/templates/hpa.yaml b/charts/opentelemetry-collector/templates/hpa.yaml
index 4b64459..2ed8b3b 100644
--- a/charts/opentelemetry-collector/templates/hpa.yaml
+++ b/charts/opentelemetry-collector/templates/hpa.yaml
@@ -3,7 +3,7 @@ apiVersion: autoscaling/v2
 kind: HorizontalPodAutoscaler
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 spec:
diff --git a/charts/opentelemetry-collector/templates/ingress.yaml b/charts/opentelemetry-collector/templates/ingress.yaml
index 0a5a4ef..be14bac 100644
--- a/charts/opentelemetry-collector/templates/ingress.yaml
+++ b/charts/opentelemetry-collector/templates/ingress.yaml
@@ -9,7 +9,7 @@ metadata:
   {{- else }}
   name: {{ include "opentelemetry-collector.fullname" $ }}
   {{- end }}
-  namespace: {{ template "opentelemetry-collector.namespace" $ }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" $ | nindent 4 }}
     {{- include "opentelemetry-collector.component" $ | nindent 4 }}
diff --git a/charts/opentelemetry-collector/templates/pdb.yaml b/charts/opentelemetry-collector/templates/pdb.yaml
index c386a47..a695f21 100644
--- a/charts/opentelemetry-collector/templates/pdb.yaml
+++ b/charts/opentelemetry-collector/templates/pdb.yaml
@@ -3,7 +3,7 @@ apiVersion: {{ include "podDisruptionBudget.apiVersion" . }}
 kind: PodDisruptionBudget
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 spec:
diff --git a/charts/opentelemetry-collector/templates/podmonitor.yaml b/charts/opentelemetry-collector/templates/podmonitor.yaml
index 782e8fa..7969754 100644
--- a/charts/opentelemetry-collector/templates/podmonitor.yaml
+++ b/charts/opentelemetry-collector/templates/podmonitor.yaml
@@ -3,7 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: PodMonitor
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.podMonitor.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/prometheusrule.yaml b/charts/opentelemetry-collector/templates/prometheusrule.yaml
index d6446ab..8311745 100644
--- a/charts/opentelemetry-collector/templates/prometheusrule.yaml
+++ b/charts/opentelemetry-collector/templates/prometheusrule.yaml
@@ -3,7 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: PrometheusRule
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.prometheusRule.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/service.yaml b/charts/opentelemetry-collector/templates/service.yaml
index c97ad24..41af984 100644
--- a/charts/opentelemetry-collector/templates/service.yaml
+++ b/charts/opentelemetry-collector/templates/service.yaml
@@ -3,7 +3,7 @@ apiVersion: v1
 kind: Service
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- include "opentelemetry-collector.component" . | nindent 4 }}
diff --git a/charts/opentelemetry-collector/templates/serviceaccount.yaml b/charts/opentelemetry-collector/templates/serviceaccount.yaml
index 3240acb..b45d4e8 100644
--- a/charts/opentelemetry-collector/templates/serviceaccount.yaml
+++ b/charts/opentelemetry-collector/templates/serviceaccount.yaml
@@ -3,7 +3,7 @@ apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: {{ include "opentelemetry-collector.serviceAccountName" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- if .Values.serviceAccount.annotations }}
diff --git a/charts/opentelemetry-collector/templates/servicemonitor.yaml b/charts/opentelemetry-collector/templates/servicemonitor.yaml
index 8acca4c..c81e28a 100644
--- a/charts/opentelemetry-collector/templates/servicemonitor.yaml
+++ b/charts/opentelemetry-collector/templates/servicemonitor.yaml
@@ -3,7 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/statefulset.yaml b/charts/opentelemetry-collector/templates/statefulset.yaml
index 3552a4e..519ed77 100644
--- a/charts/opentelemetry-collector/templates/statefulset.yaml
+++ b/charts/opentelemetry-collector/templates/statefulset.yaml
@@ -3,7 +3,7 @@ apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
-  namespace: {{ template "opentelemetry-collector.namespace" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- if .Values.annotations }}
diff --git a/charts/opentelemetry-collector/values.schema.json b/charts/opentelemetry-collector/values.schema.json
index 0a1684a..5d78b61 100644
--- a/charts/opentelemetry-collector/values.schema.json
+++ b/charts/opentelemetry-collector/values.schema.json
@@ -35,6 +35,10 @@
       "description": "Override fully qualified app name.",
       "type": "string"
     },
+    "defaultNamespace": {
+      "description": "Override default namespace of the helm chart and managed resources.",
+      "type": "string"
+    },
     "mode": {
       "type": "string",
       "enum": ["daemonset", "deployment", "statefulset", ""]
diff --git a/charts/opentelemetry-collector/values.yaml b/charts/opentelemetry-collector/values.yaml
index 28abd61..e5df2a6 100644
--- a/charts/opentelemetry-collector/values.yaml
+++ b/charts/opentelemetry-collector/values.yaml
@@ -5,6 +5,7 @@
 sourceRegistry: "783794618700.dkr.ecr.us-west-2.amazonaws.com"
 nameOverride: ""
 fullnameOverride: ""
+defaultNamespace: "observability"
 
 # Valid values are "daemonset", "deployment", and "statefulset".
 mode: ""
-- 
2.43.0

