From 62f106c4e4f2f545d08b9a994f9626a40655868f Mon Sep 17 00:00:00 2001
From: "Ostosh, Ivy" <ivyjin@amazon.com>
Date: Wed, 14 Sep 2022 10:44:03 -0500
Subject: [PATCH] Add namespace to charts

---
 charts/opentelemetry-collector/templates/configmap-agent.yaml | 1 +
 .../templates/configmap-statefulset.yaml                      | 1 +
 charts/opentelemetry-collector/templates/configmap.yaml       | 1 +
 charts/opentelemetry-collector/templates/daemonset.yaml       | 1 +
 charts/opentelemetry-collector/templates/deployment.yaml      | 1 +
 charts/opentelemetry-collector/templates/hpa.yaml             | 1 +
 charts/opentelemetry-collector/templates/ingress.yaml         | 1 +
 charts/opentelemetry-collector/templates/pdb.yaml             | 1 +
 charts/opentelemetry-collector/templates/podmonitor.yaml      | 1 +
 charts/opentelemetry-collector/templates/prometheusrule.yaml  | 1 +
 charts/opentelemetry-collector/templates/service.yaml         | 1 +
 charts/opentelemetry-collector/templates/serviceaccount.yaml  | 1 +
 charts/opentelemetry-collector/templates/servicemonitor.yaml  | 1 +
 charts/opentelemetry-collector/templates/statefulset.yaml     | 1 +
 charts/opentelemetry-collector/values.schema.json             | 4 ++++
 charts/opentelemetry-collector/values.yaml                    | 1 +
 16 files changed, 19 insertions(+)

diff --git a/charts/opentelemetry-collector/templates/configmap-agent.yaml b/charts/opentelemetry-collector/templates/configmap-agent.yaml
index e267336..2658f7b 100644
--- a/charts/opentelemetry-collector/templates/configmap-agent.yaml
+++ b/charts/opentelemetry-collector/templates/configmap-agent.yaml
@@ -3,6 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/configmap-statefulset.yaml b/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
index 59f9f04..70d4ffe 100644
--- a/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
+++ b/charts/opentelemetry-collector/templates/configmap-statefulset.yaml
@@ -3,6 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-statefulset
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/configmap.yaml b/charts/opentelemetry-collector/templates/configmap.yaml
index 42ed59a..610179b 100644
--- a/charts/opentelemetry-collector/templates/configmap.yaml
+++ b/charts/opentelemetry-collector/templates/configmap.yaml
@@ -3,6 +3,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 data:
diff --git a/charts/opentelemetry-collector/templates/daemonset.yaml b/charts/opentelemetry-collector/templates/daemonset.yaml
index 7ea532e..975c1b5 100644
--- a/charts/opentelemetry-collector/templates/daemonset.yaml
+++ b/charts/opentelemetry-collector/templates/daemonset.yaml
@@ -3,6 +3,7 @@ apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 spec:
diff --git a/charts/opentelemetry-collector/templates/deployment.yaml b/charts/opentelemetry-collector/templates/deployment.yaml
index cad6ce0..9f41936 100644
--- a/charts/opentelemetry-collector/templates/deployment.yaml
+++ b/charts/opentelemetry-collector/templates/deployment.yaml
@@ -3,6 +3,7 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- include "opentelemetry-collector.annotations" . | nindent 2 }}
diff --git a/charts/opentelemetry-collector/templates/hpa.yaml b/charts/opentelemetry-collector/templates/hpa.yaml
index 51f2c84..d0afab1 100644
--- a/charts/opentelemetry-collector/templates/hpa.yaml
+++ b/charts/opentelemetry-collector/templates/hpa.yaml
@@ -3,6 +3,7 @@ apiVersion: autoscaling/v2beta1
 kind: HorizontalPodAutoscaler
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 spec:
diff --git a/charts/opentelemetry-collector/templates/ingress.yaml b/charts/opentelemetry-collector/templates/ingress.yaml
index 9a60601..9ae999e 100644
--- a/charts/opentelemetry-collector/templates/ingress.yaml
+++ b/charts/opentelemetry-collector/templates/ingress.yaml
@@ -11,6 +11,7 @@ metadata:
   {{- else }}
   name: {{ include "opentelemetry-collector.fullname" $ }}
   {{- end }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" $ | nindent 4 }}
     {{- include "opentelemetry-collector.component" $ | nindent 4 }}
diff --git a/charts/opentelemetry-collector/templates/pdb.yaml b/charts/opentelemetry-collector/templates/pdb.yaml
index d6761e8..a695f21 100644
--- a/charts/opentelemetry-collector/templates/pdb.yaml
+++ b/charts/opentelemetry-collector/templates/pdb.yaml
@@ -3,6 +3,7 @@ apiVersion: {{ include "podDisruptionBudget.apiVersion" . }}
 kind: PodDisruptionBudget
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
 spec:
diff --git a/charts/opentelemetry-collector/templates/podmonitor.yaml b/charts/opentelemetry-collector/templates/podmonitor.yaml
index 0343681..7969754 100644
--- a/charts/opentelemetry-collector/templates/podmonitor.yaml
+++ b/charts/opentelemetry-collector/templates/podmonitor.yaml
@@ -3,6 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: PodMonitor
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}-agent
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.podMonitor.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/prometheusrule.yaml b/charts/opentelemetry-collector/templates/prometheusrule.yaml
index 2f2ffe7..d34f70e 100644
--- a/charts/opentelemetry-collector/templates/prometheusrule.yaml
+++ b/charts/opentelemetry-collector/templates/prometheusrule.yaml
@@ -3,6 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: PrometheusRule
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.prometheusRule.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/service.yaml b/charts/opentelemetry-collector/templates/service.yaml
index eeb1178..8dac959 100644
--- a/charts/opentelemetry-collector/templates/service.yaml
+++ b/charts/opentelemetry-collector/templates/service.yaml
@@ -3,6 +3,7 @@ apiVersion: v1
 kind: Service
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- include "opentelemetry-collector.component" . | nindent 4 }}
diff --git a/charts/opentelemetry-collector/templates/serviceaccount.yaml b/charts/opentelemetry-collector/templates/serviceaccount.yaml
index 5daa658..ccbed4e 100644
--- a/charts/opentelemetry-collector/templates/serviceaccount.yaml
+++ b/charts/opentelemetry-collector/templates/serviceaccount.yaml
@@ -3,6 +3,7 @@ apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: {{ include "opentelemetry-collector.serviceAccountName" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- with .Values.serviceAccount.annotations }}
diff --git a/charts/opentelemetry-collector/templates/servicemonitor.yaml b/charts/opentelemetry-collector/templates/servicemonitor.yaml
index dae68d2..bfa63d8 100644
--- a/charts/opentelemetry-collector/templates/servicemonitor.yaml
+++ b/charts/opentelemetry-collector/templates/servicemonitor.yaml
@@ -3,6 +3,7 @@ apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
     {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
diff --git a/charts/opentelemetry-collector/templates/statefulset.yaml b/charts/opentelemetry-collector/templates/statefulset.yaml
index d3b06e9..377b6bd 100644
--- a/charts/opentelemetry-collector/templates/statefulset.yaml
+++ b/charts/opentelemetry-collector/templates/statefulset.yaml
@@ -3,6 +3,7 @@ apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: {{ include "opentelemetry-collector.fullname" . }}
+  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
   labels:
     {{- include "opentelemetry-collector.labels" . | nindent 4 }}
   {{- include "opentelemetry-collector.annotations" . | nindent 2 }}
diff --git a/charts/opentelemetry-collector/values.schema.json b/charts/opentelemetry-collector/values.schema.json
index 3f4d94f..c263021 100644
--- a/charts/opentelemetry-collector/values.schema.json
+++ b/charts/opentelemetry-collector/values.schema.json
@@ -23,6 +23,10 @@
       "description": "Override fully qualified app name.",
       "type": "string"
     },
+    "defaultNamespace": {
+      "description": "Override default namespace of the helm chart and managed resources.",
+      "type": "string"
+    },
     "mode": {
       "type": "string",
       "enum": [
diff --git a/charts/opentelemetry-collector/values.yaml b/charts/opentelemetry-collector/values.yaml
index 69df2f5..0ed6dda 100644
--- a/charts/opentelemetry-collector/values.yaml
+++ b/charts/opentelemetry-collector/values.yaml
@@ -5,6 +5,7 @@
 sourceRegistry: "783794618700.dkr.ecr.us-west-2.amazonaws.com"
 nameOverride: ""
 fullnameOverride: ""
+defaultNamespace: "observability"
 
 # Valid values are "daemonset", "deployment", and "statefulset".
 mode: ""
-- 
2.31.0

