From e95d120c8fb1f3fe52078a2ae1d3ccca0253eca7 Mon Sep 17 00:00:00 2001
From: "Ostosh, Ivy" <ivyjin@amazon.com>
Date: Fri, 27 Jan 2023 14:54:12 -0600
Subject: [PATCH] Update default values

---
 .../values.schema.json                        |  5 +-
 charts/opentelemetry-collector/values.yaml    | 57 +------------------
 2 files changed, 4 insertions(+), 58 deletions(-)

diff --git a/charts/opentelemetry-collector/values.schema.json b/charts/opentelemetry-collector/values.schema.json
index eedb8e7..f2d7323 100644
--- a/charts/opentelemetry-collector/values.schema.json
+++ b/charts/opentelemetry-collector/values.schema.json
@@ -772,8 +772,5 @@
         }
       }
     }
-  },
-  "required": [
-    "mode"
-  ]
+  }
 }
diff --git a/charts/opentelemetry-collector/values.yaml b/charts/opentelemetry-collector/values.yaml
index 2f7da11..ff37ea3 100644
--- a/charts/opentelemetry-collector/values.yaml
+++ b/charts/opentelemetry-collector/values.yaml
@@ -8,7 +8,7 @@ fullnameOverride: ""
 defaultNamespace: "observability"
 
 # Valid values are "daemonset", "deployment", and "statefulset".
-mode: ""
+mode: "daemonset"
 
 # Handles basic configuration of components that
 # also require k8s modifications to work correctly.
@@ -64,7 +64,8 @@ configMap:
 # For example, {{ REDACTED_EMAIL }} becomes {{` {{ REDACTED_EMAIL }} `}}.
 config:
   exporters:
-    logging: {}
+    logging:
+      loglevel: info
   extensions:
     # The health_check extension is mandatory for this chart.
     # Without the health_check extension the collector will fail the readiness and liveliness probes.
@@ -76,14 +77,6 @@ config:
     # If set to null, will be overridden with values based on k8s resource limits
     memory_limiter: null
   receivers:
-    jaeger:
-      protocols:
-        grpc:
-          endpoint: ${MY_POD_IP}:14250
-        thrift_http:
-          endpoint: ${MY_POD_IP}:14268
-        thrift_compact:
-          endpoint: ${MY_POD_IP}:6831
     otlp:
       protocols:
         grpc:
@@ -98,8 +91,6 @@ config:
             static_configs:
               - targets:
                   - ${MY_POD_IP}:8888
-    zipkin:
-      endpoint: ${MY_POD_IP}:9411
   service:
     telemetry:
       metrics:
@@ -108,14 +99,6 @@ config:
       - health_check
       - memory_ballast
     pipelines:
-      logs:
-        exporters:
-          - logging
-        processors:
-          - memory_limiter
-          - batch
-        receivers:
-          - otlp
       metrics:
         exporters:
           - logging
@@ -125,16 +108,6 @@ config:
         receivers:
           - otlp
           - prometheus
-      traces:
-        exporters:
-          - logging
-        processors:
-          - memory_limiter
-          - batch
-        receivers:
-          - otlp
-          - jaeger
-          - zipkin
 
 image:
   # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
@@ -225,30 +198,6 @@ ports:
     servicePort: 4318
     hostPort: 4318
     protocol: TCP
-  jaeger-compact:
-    enabled: true
-    containerPort: 6831
-    servicePort: 6831
-    hostPort: 6831
-    protocol: UDP
-  jaeger-thrift:
-    enabled: true
-    containerPort: 14268
-    servicePort: 14268
-    hostPort: 14268
-    protocol: TCP
-  jaeger-grpc:
-    enabled: true
-    containerPort: 14250
-    servicePort: 14250
-    hostPort: 14250
-    protocol: TCP
-  zipkin:
-    enabled: true
-    containerPort: 9411
-    servicePort: 9411
-    hostPort: 9411
-    protocol: TCP
   metrics:
     # The metrics port is disabled by default. However you need to enable the port
     # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
-- 
2.31.0

