{{- if .Values.envoy.deploy -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envoy.name }}
  namespace: {{ .Values.namespace }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: tink_server_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.tinkServer.port.hostPort }}
        filter_chains:
        - filters:
          - name: envoy.tink_grpc_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy 
              stat_prefix: ingress_http
              cluster: tink_server_cluster
              max_connect_attempts: 10
      - name: hegel_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.hegel.port.hostPort }}
        filter_chains:
        - filters:
          - name: envoy.hegel_http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              use_remote_address: true
              skip_xff_append: false
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: hegel
                      cluster: hegel_cluster
                      timeout: 60s
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: tink_server_cluster
        connect_timeout: 0.25s
        type: strict_dns
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        load_assignment:
          cluster_name: tink_server_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.tinkServer.name }}
                    port_value: {{ .Values.tinkServer.port.hostPort }}
      - name: hegel_cluster
        connect_timeout: 0.25s
        type: strict_dns
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        load_assignment:
          cluster_name: tink_server_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.hegel.name }}
                    port_value: {{ .Values.hegel.port.hostPort }}
{{- end -}}
