version: 0.2

env:
  variables:
    HAS_S3_ARTIFACTS: ""

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh

  build:
    commands:
    - if $(make check-project-path-exists); then make download-binaries-from-bucket release -C $PROJECT_PATH; fi
