{{- if .Values.loadBalancer.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubevip.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubevip.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubevip.name }}
  namespace: {{ .Values.namespace }}
{{- end }}
