{{- if .Values.rufio.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rufio.rufioSecretsViewerRoleBindingName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rufio.rufioSecretsViewerRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rufio.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end }}
