---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-eks-anywhere
  labels:
    app: test-eks-anywhere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-eks-anywhere
  template:
    metadata:
      labels:
        app: test-eks-anywhere
    spec:
      containers:
      - name: hello
        image: public.ecr.aws/eks-anywhere/test-eks-anywhere:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /config
          name: foo
        - mountPath: /secrets
          name: bar
      volumes:
      - name: foo
        configMap:
          name: foo
      - name: bar
        secret:
          secretName: bar
---
apiVersion: v1
kind: Service
metadata:
  name: test-eks-anywhere
spec:
  type: NodePort
  selector:
    app: test-eks-anywhere
  ports:
    - port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: bar
data:
  bar: cXV1eA== # quux
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
  foo: baz
