version: 0.2

run-as: imagebuilder

env:
  variables:
    HOME: "/home/imagebuilder"
    CLI_FOLDER: "projects/aws/image-builder"
    GOPATH: "/home/imagebuilder/go"

phases:
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - if make check-for-supported-release-branch -C $PROJECT_PATH && make check-for-release-branch-skip -C $PROJECT_PATH; then make binaries -C $CLI_FOLDER && make release IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=ami RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH; fi
