version: 0.2

run-as: imagebuilder

env:
  variables:
    HOME: "/home/imagebuilder"

phases:
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - make release IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=ami RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH
