version: 0.2

run-as: imagebuilder

env:
  variables:
    HOME: "/home/imagebuilder"
  secrets-manager:
    GOVC_DATACENTER: "vsphere_ci_beta_connection:vsphere_datacenter"
    GOVC_URL: "vsphere_ci_beta_connection:vsphere_url"
    GOVC_USERNAME: "vsphere_ci_beta_connection:vsphere_username"
    GOVC_PASSWORD: "vsphere_ci_beta_connection:vsphere_password"
    VSPHERE_CONNECTION_DATA: "vsphere_ci_beta_connection:vsphere_connection_data"

phases:
  # On AL2, the Cargo build system requires the openssl-devel package
  # for installing OpenSSL headers/libraries
  install:
    run-as: root
    commands:
      - yum install -y openssl-devel

  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - make release-ova-ubuntu-2004-1-20 -C $PROJECT_PATH

  post_build:
    commands:
      - make upload-artifacts-1-20 -C $PROJECT_PATH
      - make release-ova-bottlerocket-1-20 -C $PROJECT_PATH