version: 0.2

env:
  variables:
    CLI_FOLDER: "projects/aws/image-builder"

phases:
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - make binaries -C $CLI_FOLDER && cp $CLI_FOLDER/_output/bin/image-builder/linux-$(go env GOARCH)/image-builder $HOME
      - if make check-for-supported-release-branch -C $PROJECT_PATH; then make release IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=cloudstack RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH; fi
