version: 0.2

run-as: imagebuilder

env:
  variables:
    HOME: "/home/imagebuilder"
    CLI_FOLDER: "projects/aws/image-builder"
    GOPATH: "/home/imagebuilder/go"
  secrets-manager:
    GOVC_DATACENTER: "vsphere_dev_beta_connection:vsphere_datacenter"
    GOVC_URL: "vsphere_dev_beta_connection:vsphere_url"
    GOVC_USERNAME: "vsphere_dev_beta_connection:vsphere_username"
    GOVC_PASSWORD: "vsphere_dev_beta_connection:vsphere_password"
    VSPHERE_CONNECTION_DATA: "vsphere_dev_beta_connection:vsphere_connection_data"

phases:
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:      
      - if make check-for-supported-release-branch IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=ova RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH && make check-for-release-branch-skip -C $PROJECT_PATH; then make binaries -C $CLI_FOLDER && make release IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=ova RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH; fi
