version: 0.2

run-as: imagebuilder

env:
  variables:
    HOME: "/home/imagebuilder"
  secrets-manager:
    GOVC_DATACENTER: "vsphere_ci_beta_connection:vsphere_datacenter"
    GOVC_URL: "vsphere_ci_beta_connection:vsphere_url"
    GOVC_USERNAME: "vsphere_ci_beta_connection:vsphere_username"
    GOVC_PASSWORD: "vsphere_ci_beta_connection:vsphere_password"
    VSPHERE_CONNECTION_DATA: "vsphere_ci_beta_connection:vsphere_connection_data"

phases:
  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - make release IMAGE_OS=$IMAGE_OS IMAGE_FORMAT=ova RELEASE_BRANCH=$RELEASE_BRANCH -C $PROJECT_PATH
