kernel:
  image: ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinkerbell/hook-kernel:latest
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /run:/run
     - /var/lib/dhcpcd:/var/lib/dhcpcd
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /run:/run
     - /var/lib/dhcpcd:/var/lib/dhcpcd
  - name: ntpd
    image: linuxkit/openntpd:v0.8
    binds:
     - /var/run:/var/run
  - name: docker
    image: ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinkerbell/hook-docker:latest
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
     - /var/run/docker:/var/run
     - /var/run/worker:/worker
     - /dev/console:/dev/console
     - /dev:/dev
     - /var/run/images:/var/lib/docker
    runtime:
      mkdir:
        - /var/run/images
        - /var/run/docker
        - /var/run/worker
  - name: bootkit
    image: ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinkerbell/hook-bootkit:latest
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker
files:
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
