apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs-cstor
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "eksa-node04"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-24cccaa7cb0d60d80a91454ac55f55a4"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "eksa-node03"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-8a0d969dda7ce742b626ba2cef471fd2"
     poolConfig:
       dataRaidGroupType: "stripe"

