apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: seifsall
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "10.61.248.243"
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: seifsall-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: seifsall
  kubernetesVersion: "1.22"
  managementCluster:
    name: seifsall
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: seifsall
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: seifsall
spec:
  tinkerbellIP: "10.61.248.244"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: seifsall-cp
spec:
  hardwareSelector:
    type: cp
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeJPEr2u9qZaJ7b9ugslDSaApgbtEINceEcWzZCLPvNCupYyQZphwoBsBz1YgLnNZuWMPb2vvxtEyt3Pda+gnoagVfOgPFOY2NAoTljkcDp0uCobZ49sZCJMRTxsFFQmkX67o6Nuep604ldbd2pliepjTE7AV0fV7/v5qEdKdPhT2XNVuqjSeKv9jIgW9c/jdnNwBPVp5Fs/GPZZ2oB65aYNFdX5Be0Whwp5ke/6U1+rpXU0j0iWrbBOBV9AMfeBh3SzDVheFzDNSSHRmLR7b9m5WEQ4vgu/HRK+RhlZZWP0YB2bCp+hmRuld6NRsbAa7oRTj85X6kYLUMJ+6H/Pu1

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: seifsall
spec:
  hardwareSelector:
    type: worker
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeJPEr2u9qZaJ7b9ugslDSaApgbtEINceEcWzZCLPvNCupYyQZphwoBsBz1YgLnNZuWMPb2vvxtEyt3Pda+gnoagVfOgPFOY2NAoTljkcDp0uCobZ49sZCJMRTxsFFQmkX67o6Nuep604ldbd2pliepjTE7AV0fV7/v5qEdKdPhT2XNVuqjSeKv9jIgW9c/jdnNwBPVp5Fs/GPZZ2oB65aYNFdX5Be0Whwp5ke/6U1+rpXU0j0iWrbBOBV9AMfeBh3SzDVheFzDNSSHRmLR7b9m5WEQ4vgu/HRK+RhlZZWP0YB2bCp+hmRuld6NRsbAa7oRTj85X6kYLUMJ+6H/Pu1
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: seifsall-etcd
spec:
  hardwareSelector:
    type: worker
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeJPEr2u9qZaJ7b9ugslDSaApgbtEINceEcWzZCLPvNCupYyQZphwoBsBz1YgLnNZuWMPb2vvxtEyt3Pda+gnoagVfOgPFOY2NAoTljkcDp0uCobZ49sZCJMRTxsFFQmkX67o6Nuep604ldbd2pliepjTE7AV0fV7/v5qEdKdPhT2XNVuqjSeKv9jIgW9c/jdnNwBPVp5Fs/GPZZ2oB65aYNFdX5Be0Whwp5ke/6U1+rpXU0j0iWrbBOBV9AMfeBh3SzDVheFzDNSSHRmLR7b9m5WEQ4vgu/HRK+RhlZZWP0YB2bCp+hmRuld6NRsbAa7oRTj85X6kYLUMJ+6H/Pu1
---
