{{- if .Values.tinkServer.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.tinkServer.roleBindingName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.tinkServer.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.tinkServer.name }}
    namespace: {{ .Values.namespace }}
{{- end }}
