# Default values for tinkerbell.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: tink-system
createNamespace: true

boots:
  deploy: true
  name: boots
  image: public.ecr.aws/eks-anywhere/tinkerbell/boots:94e4b4899b383e28b6002750b14e254cfbbdd81f-eks-a-12
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: ["-dhcp-addr=0.0.0.0:67"]
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: boots-role
  roleBindingName: boots-rolebinding
  env: []
  

hegel:
  deploy: true
  name: hegel
  image: public.ecr.aws/eks-anywhere/tinkerbell/hegel:7b286fdc8e8fa91a6e9a179a5494b6ee29fce17b-eks-a-12
  imagePullPolicy: IfNotPresent
  replicas: 1
  port:
    hostPortEnabled: false
    hostPort: 50061
  args: ["--grpc-use-tls=false"]
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: hegel-role
  roleBindingName: hegel-rolebinding
  env:
  - name: TRUSTED_PROXIES
    value: 192.168.0.0/16

rufio:
  deploy: true
  name: rufio-controller-manager
  image: public.ecr.aws/eks-anywhere/tinkerbell/rufio:a4053e5c1e7f32fb5c0a9962846c219c3ef8aaf3-eks-a-12
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  serviceAccountName: rufio-controller-manager
  rufioLeaderElectionRoleName: rufio-leader-election-role
  rufioSecretsViewerRoleName: rufio-secrets-viewer-role
  managerRoleName: rufio-manager-role
  rufioLeaderElectionRoleBindingName: rufio-leader-election-rolebinding
  rufioSecretsViewerRoleBindingName: rufio-secrets-viewer-rolebinding
  managerRoleBindingName: rufio-manager-rolebinding
  managerConfigmapName: rufio-manager-config

tinkController:
  deploy: true
  name: tink-controller-manager
  image: public.ecr.aws/eks-anywhere/tinkerbell/tink/tink-controller:19b68beab1a902846c10ee3422cafb4fd5c3307e-eks-a-12
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-controller-manager-role
  roleBindingName: tink-controller-manager-rolebinding
  tinkLeaderElectionRoleName: tink-leader-election-role
  tinkLeaderElectionRoleBindingName: tink-leader-election-rolebinding

tinkServer:
  deploy: true
  name: tink-server
  image: public.ecr.aws/eks-anywhere/tinkerbell/tink/tink-server:19b68beab1a902846c10ee3422cafb4fd5c3307e-eks-a-12
  imagePullPolicy: IfNotPresent
  replicas: 1
  port:
    hostPortEnabled: false
    hostPort: 42113
  args: ["--tls=false"]
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-server-role
  roleBindingName: tink-server-rolebinding

envoy:
  deploy: true
  name: envoy
  image: public.ecr.aws/l0g8r8j6/envoyproxy/envoy:v1.22.2.0-prod-eks-a-v0.0.0-dev-build.3645
  imagePullPolicy: IfNotPresent
  externalIp: 192.168.0.10

kubevip:
  deploy: true
  name: kube-vip
  image: public.ecr.aws/l0g8r8j6/kube-vip/kube-vip:v0.5.0-eks-a-v0.0.0-dev-build.3614
  imagePullPolicy: IfNotPresent
  roleName: kube-vip-role
  roleBindingName: kube-vip-rolebinding
  loadBalancerClass: kube-vip.io/kube-vip-class
