version: 0.2

phases:
  pre_build:
    commands:
    - ./build/lib/setup.sh
    - docker run --rm registry:2

  build:
    commands:
    - make release -C $PROJECT_PATH

  post_build:
    commands:
    - make upload-artifacts -C $PROJECT_PATH